version: "3.8"
services:
  nginx:
      build: ./nginx
      container_name: nginx
      ports:
        - 8080:8080
      networks:
        - app-network
      depends_on:
        - backend
  backend:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
      target: production
    container_name: flask-app
    ports:
      - 5000:5000
    networks:
      - app-network


networks:
  app-network: